# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='regex_display',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='regex_format',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
