# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false
env:
  matrix:
    # - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    # - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    # - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
    # - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - DISTRIB="ubuntu" PYTHON_VERSION="3.5" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  # - source tests/travis_install.sh
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
before_script:
  - git config --global user.email "travis.github@totalgood.com"
  - git config --global user.name "Travis Testing for Total Good civicu_app"
script:
  - python manage.py test
  - python setup.py test
after_success:
  - codecov
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
