sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - mopidy

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 graphviz-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad python-gst-1.0"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"
