
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-20T22:42:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cba7a9c3a7651016c61db4ce7d99c337381d35f9",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
