# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 09:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text=b'Customer ID', max_length=50)),
                ('menu', models.CharField(help_text=b'Menu', max_length=50)),
                ('page', models.CharField(help_text=b'Page Name', max_length=100)),
                ('url', models.CharField(blank=True, help_text=b'Url', max_length=500)),
                ('module_path', models.CharField(help_text=b'Page Name', max_length=100)),
                ('parent_record', models.CharField(blank=True, help_text=b'Parent Record', max_length=100, null=True)),
                ('child_records', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text=b'Child Records', null=True, size=None)),
            ],
            options={
                'db_table': 'page_models',
            },
        ),
        migrations.CreateModel(
            name='QueryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('qtype', models.CharField(choices=[(b'', b''), (b'Private', b'Private'), (b'Public', b'Public')], default=b'Private', max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('effective_from', models.DateTimeField(blank=True, help_text=b'Effective From', null=True)),
                ('expression', django.contrib.postgres.fields.jsonb.JSONField()),
                ('records', django.contrib.postgres.fields.jsonb.JSONField()),
                ('relations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('criteria', django.contrib.postgres.fields.jsonb.JSONField()),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'query_manager',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pagemodels',
            unique_together=set([('customer_id', 'url', 'page')]),
        ),
    ]
