# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0002_delete_pagemodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymanager',
            name='has_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querymanager',
            name='limit_range',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='querymanager',
            name='select_distinct',
            field=models.BooleanField(default=False),
        ),
    ]
