# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0003_auto_20170822_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymanager',
            name='subqueries',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
