# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170904_1126'),
        ('querymanager', '0004_querymanager_subqueries'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQueryViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=30)),
                ('query_description', models.CharField(max_length=60)),
                ('query_summary', models.TextField()),
                ('file_name', models.TextField(max_length=100)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.ReqHeader')),
            ],
            options={
                'db_table': 'request_query_viewer',
            },
        ),
    ]
