!!python/object/new:agents.tools.attr_dict.AttrDict
dictitems:
  algorithm: !!python/name:agents.ppo.algorithm.PPOAlgorithm ''
  discount: 0.99
  env: InvertedPendulumBulletEnv-v0
  eval_episodes: 25
  init_logstd: -1
  init_mean_factor: 0.2
  kl_cutoff_coef: 1000
  kl_cutoff_factor: 2
  kl_init_penalty: 1
  kl_target: 0.01
  logdir: pend/20170927T100650-pybullet_pendulum
  max_length: 200
  network: !!python/name:agents.scripts.networks.ForwardGaussianPolicy ''
  network_config: {}
  num_agents: 25
  policy_layers: !!python/tuple
  - 200
  - 100
  policy_lr: 0.0001
  policy_optimizer: AdamOptimizer
  steps: 50000000.0
  update_epochs_policy: 25
  update_epochs_value: 25
  update_every: 25
  use_gpu: false
  value_layers: !!python/tuple
  - 200
  - 100
  value_lr: 0.001
  value_optimizer: AdamOptimizer
  weight_summaries:
    all: .*
    policy: .*/policy/.*
    value: .*/value/.*
state:
  _mutable: false
