
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-25T19:16:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "68cc3a7c351b95878f8bdb0e4b9531fa5b5134aa",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
