# Webroot:
files: ./files

# Serve 'index' or 'gallery' by default:
frontpage: 'index'

# thumbnail settings:
thumb_width: 450
thumb_height: 150
image_exts: ['.jpg', '.jpeg', '.png', '.bmp', '.gif']

# Cache location for internal files:
# (might go away in favor of redis)
cache: ./cache
