language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

addons:
  apt:
    packages:
    - iverilog

install:
  - pip install jinja2 pytest pytest-pythonpath

script:
  - python -m pytest tests
