# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invites_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invite',
            name='send_after',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 12, 11, 39, 889899)),
            preserve_default=False,
        ),
    ]
