
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-14T09:54:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b0d11b1e67d63801943fb0964fc64aa764a9542",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
