
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-18T10:37:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "724ba222e3ef2788e0de9b6e7a1dc2315f1b23b8",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
