language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
#  - osx  #
# command to install dependencies
install:
- "pip install -r requirements.txt"
- "python setup.py build install"

# command to run tests
script:
- python setup.py test

deploy:
    # production pypi
  provider: pypi
  skip_cleanup: true
  user: fleming79
  password: Read1MPassword2
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    tags: true
    branch: master

