
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-14T14:19:24+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "de66ffe9f98950226750698ed2f9c66d8e1dfabc",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
