# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, verbose_name='country_code')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal_code')),
                ('place_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='place_name')),
                ('admin_name1', models.CharField(blank=True, max_length=100, null=True, verbose_name='admin_name1')),
                ('admin_code1', models.CharField(blank=True, max_length=20, null=True, verbose_name='admin_code1')),
                ('admin_name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='admin_name2')),
                ('admin_code2', models.CharField(blank=True, max_length=20, null=True, verbose_name='admin_code2')),
                ('admin_name3', models.CharField(blank=True, max_length=100, null=True, verbose_name='admin_name3')),
                ('admin_code3', models.CharField(blank=True, max_length=20, null=True, verbose_name='admin_code3')),
            ],
            options={
                'verbose_name': 'Postal code',
                'verbose_name_plural': 'Postal codes',
            },
        ),
    ]
