# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='end',
            new_name='eva_end',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start',
            new_name='eva_start',
        ),
        migrations.RemoveField(
            model_name='spacewalker',
            name='objectives',
        ),
        migrations.AddField(
            model_name='activity',
            name='airlock_enter',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Airlock Enter'),
        ),
        migrations.AddField(
            model_name='activity',
            name='airlock_exit',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Airlock Exit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='spacewalker',
            name='medicals_after',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Medicals After EVA'),
        ),
        migrations.AddField(
            model_name='spacewalker',
            name='medicals_before',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Medicals Before EVA'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(default=None, help_text='Where the EVA took place', on_delete=django.db.models.deletion.CASCADE, to='extravehicular.Location', verbose_name='Location'),
        ),
    ]
