language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"

sudo: true

before_install:
  - pip install coverage
  - pip install nose

install:
  - python setup.py install

script: nosetests

after_success:
 - coverage run tests
 - bash <(curl -s https://codecov.io/bash)

