
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-14T14:23:02+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "420e9e2c0d8150c800f8b3c27cefe7a43f0923eb",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
