# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.TextField(default='')),
                ('data2', models.TextField(default='')),
                ('output', models.TextField(default='')),
                ('user_id', models.TextField(default='')),
                ('amount', models.TextField(default='')),
                ('currency', models.TextField(default='')),
                ('impression_id', models.TextField(default='')),
                ('timestamp', models.TextField(default='')),
                ('hash', models.TextField(default='')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
