- src: https://github.com/Oefenweb/ansible-fail2ban
  path: roles/library

- src: dev-sec.ssh-hardening
  path: roles/library

- src: https://github.com/
  path: roles/library

- src: https://github.com/jlund/ansible-go
  path: roles/library