heat_template_version: pike

description: >
  OpenStack containerized Nova Migration Target service

parameters:
  DockerNovaComputeImage:
    description: image
    type: string
  DockerNovaLibvirtConfigImage:
    description: The container image to use for the nova_libvirt config_volume
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  DockerNovaMigrationSshdPort:
    default: 2022
    description: Port that dockerized nova migration target sshd service
                 binds to.
    type: number

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  SshdBase:
    type: ../../puppet/services/sshd.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

  NovaMigrationTargetBase:
    type: ../../puppet/services/nova-migration-target.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Nova Migration Target service.
    value:
      service_name: nova_migration_target
      config_settings:
        map_merge:
          - get_attr: [SshdBase, role_data, config_settings]
          - get_attr: [NovaMigrationTargetBase, role_data, config_settings]
          - tripleo.nova_migration_target.firewall_rules:
              '113 nova_migration_target':
                dport:
                  - {get_param: DockerNovaMigrationSshdPort}
      step_config: &step_config
        list_join:
          - "\n"
          - - get_attr: [SshdBase, role_data, step_config]
            - get_attr: [NovaMigrationTargetBase, role_data, step_config]
      puppet_config:
        config_volume: nova_libvirt
        step_config: *step_config
        config_image: {get_param: DockerNovaLibvirtConfigImage}
      kolla_config:
        /var/lib/kolla/config_files/nova-migration-target.json:
          command:
            str_replace:
              template: "/usr/sbin/sshd -D -p SSHDPORT"
              params:
                SSHDPORT: {get_param: DockerNovaMigrationSshdPort}
          config_files:
            - source: "/var/lib/kolla/config_files/src/*"
              dest: "/"
              merge: true
              preserve_properties: true
            - source: /host-ssh/ssh_host_*_key
              dest: /etc/ssh/
              owner: "root"
              perm: "0600"
      docker_config:
        step_4:
          nova_migration_target:
            image: {get_param: DockerNovaComputeImage}
            net: host
            privileged: true
            user: root
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/nova-migration-target.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/puppet-generated/nova_libvirt/:/var/lib/kolla/config_files/src:ro
                  - /etc/ssh/:/host-ssh/:ro
                  - /run:/run
                  - /var/lib/nova:/var/lib/nova
            environment:
             - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
