
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-26T08:21:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "832bfe082dd337a48126143da74baa4cda735284",
 "version": "2.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
