
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-27T18:29:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6077f2c623ae3c428976c0dcf3b5f99549af1c68",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
