
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-10T12:42:25-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "47e7302af5640b2aef28b66e38bf94dcedeff4f3",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
