version: 2

jobs:

  test-2.7:
    docker:
      - image: lowieh/docker-python-gcp:2.7
    steps:
      - checkout
      - restore_cache:
          key: deps-test-2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install codecov setuptools_scm
            pip install -r requirements.txt
      - save_cache:
          key: deps-test-2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=edmunds setup.py test
      - run:
          command: |
            . venv/bin/activate
            codecov --required

  test-3.4:
    docker:
      - image: lowieh/docker-python-gcp:3.4
    steps:
      - checkout
      - restore_cache:
          key: deps-test-3.4-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install codecov setuptools_scm
            pip install -r requirements.txt
      - save_cache:
          key: deps-test-3.4-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=edmunds setup.py test
      - run:
          command: |
            . venv/bin/activate
            codecov --required

  test-3.5:
    docker:
      - image: lowieh/docker-python-gcp:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps-test-3.5-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install codecov setuptools_scm
            pip install -r requirements.txt
      - save_cache:
          key: deps-test-3.5-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=edmunds setup.py test
      - run:
          command: |
            . venv/bin/activate
            codecov --required

  test-3.6:
    docker:
      - image: lowieh/docker-python-gcp:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-test-3.6-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            # Update setuptools to avoid this issue: https://github.com/linsomniac/python-memcached/issues/103
            pip install -U setuptools
            pip install codecov setuptools_scm
            pip install -r requirements.txt
      - save_cache:
          key: deps-test-3.6-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=edmunds setup.py test
      - run:
          command: |
            . venv/bin/activate
            codecov --required

  update-docs:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install mkdocs
      - run:
          command: |
            rm -rf site
            mkdir -p site/.circleci
            cp .circleci/gh-pages.config.yml site/.circleci/config.yml
      - deploy:
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "sayhi@circleci.com"
            mkdocs gh-deploy --dirty


workflows:
  version: 2

  test:
    jobs:
      - test-2.7
      - test-3.4
      - test-3.5
      - test-3.6
      - update-docs:
          filters:
            branches:
              only: master
          requires:
            - test-2.7
            - test-3.4
            - test-3.5
            - test-3.6
