
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-13T10:22:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cae5bb21dba9023a3be9a1a8bb81c9633409daad",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
