
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-09T11:19:34-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4897bf436228bb94cd26401e8b5a0d937ca1184",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
