# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 09:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('reviewer', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('test_cases', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=30)),
                ('review_status', models.CharField(max_length=150, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('request_for_deployment_on', models.DateTimeField(null=True)),
                ('deployed_on', models.DateTimeField(null=True)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('submitted_by', models.CharField(max_length=100, null=True)),
                ('reviewed_by', models.CharField(max_length=100, null=True)),
                ('deployed_by', models.CharField(max_length=100, null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
            ],
            options={
                'db_table': 'addon',
            },
        ),
        migrations.CreateModel(
            name='AddonHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_dttm', models.DateTimeField(auto_now_add=True)),
                ('audit_user', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.Addon')),
            ],
            options={
                'db_table': 'addon_history',
            },
        ),
        migrations.CreateModel(
            name='MenuStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
            ],
            options={
                'db_table': 'menu_structure',
            },
        ),
    ]
