#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='modeltee',
      version='0.1',
      description='A framework for automating software releases',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://gitlab.com/takluyver/modeltee',
      py_modules=['modeltee'],
     )
