# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:25
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0012_auto_20170331_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
