# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='HSAdminRefreshProtocol.proto',
  package='hadoop.mapreduce',
  serialized_pb='\n\x1cHSAdminRefreshProtocol.proto\x12\x10hadoop.mapreduce\"\x1e\n\x1cRefreshAdminAclsRequestProto\"\x1f\n\x1dRefreshAdminAclsResponseProto\"#\n!RefreshLoadedJobCacheRequestProto\"$\n\"RefreshLoadedJobCacheResponseProto\")\n\'RefreshJobRetentionSettingsRequestProto\"*\n(RefreshJobRetentionSettingsResponseProto\")\n\'RefreshLogRetentionSettingsRequestProto\"*\n(RefreshLogRetentionSettingsResponseProto2\xc7\x04\n\x1dHSAdminRefreshProtocolService\x12s\n\x10refreshAdminAcls\x12..hadoop.mapreduce.RefreshAdminAclsRequestProto\x1a/.hadoop.mapreduce.RefreshAdminAclsResponseProto\x12\x82\x01\n\x15refreshLoadedJobCache\x12\x33.hadoop.mapreduce.RefreshLoadedJobCacheRequestProto\x1a\x34.hadoop.mapreduce.RefreshLoadedJobCacheResponseProto\x12\x94\x01\n\x1brefreshJobRetentionSettings\x12\x39.hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto\x1a:.hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto\x12\x94\x01\n\x1brefreshLogRetentionSettings\x12\x39.hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto\x1a:.hadoop.mapreduce.RefreshLogRetentionSettingsResponseProtoBP\n\'org.apache.hadoop.mapreduce.v2.hs.protoB\x1cHSAdminRefreshProtocolProtos\x88\x01\x01\x90\x01\x01\xa0\x01\x01')




_REFRESHADMINACLSREQUESTPROTO = descriptor.Descriptor(
  name='RefreshAdminAclsRequestProto',
  full_name='hadoop.mapreduce.RefreshAdminAclsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=80,
)


_REFRESHADMINACLSRESPONSEPROTO = descriptor.Descriptor(
  name='RefreshAdminAclsResponseProto',
  full_name='hadoop.mapreduce.RefreshAdminAclsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=113,
)


_REFRESHLOADEDJOBCACHEREQUESTPROTO = descriptor.Descriptor(
  name='RefreshLoadedJobCacheRequestProto',
  full_name='hadoop.mapreduce.RefreshLoadedJobCacheRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=150,
)


_REFRESHLOADEDJOBCACHERESPONSEPROTO = descriptor.Descriptor(
  name='RefreshLoadedJobCacheResponseProto',
  full_name='hadoop.mapreduce.RefreshLoadedJobCacheResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=188,
)


_REFRESHJOBRETENTIONSETTINGSREQUESTPROTO = descriptor.Descriptor(
  name='RefreshJobRetentionSettingsRequestProto',
  full_name='hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=231,
)


_REFRESHJOBRETENTIONSETTINGSRESPONSEPROTO = descriptor.Descriptor(
  name='RefreshJobRetentionSettingsResponseProto',
  full_name='hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=233,
  serialized_end=275,
)


_REFRESHLOGRETENTIONSETTINGSREQUESTPROTO = descriptor.Descriptor(
  name='RefreshLogRetentionSettingsRequestProto',
  full_name='hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=277,
  serialized_end=318,
)


_REFRESHLOGRETENTIONSETTINGSRESPONSEPROTO = descriptor.Descriptor(
  name='RefreshLogRetentionSettingsResponseProto',
  full_name='hadoop.mapreduce.RefreshLogRetentionSettingsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=320,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['RefreshAdminAclsRequestProto'] = _REFRESHADMINACLSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshAdminAclsResponseProto'] = _REFRESHADMINACLSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshLoadedJobCacheRequestProto'] = _REFRESHLOADEDJOBCACHEREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshLoadedJobCacheResponseProto'] = _REFRESHLOADEDJOBCACHERESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshJobRetentionSettingsRequestProto'] = _REFRESHJOBRETENTIONSETTINGSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshJobRetentionSettingsResponseProto'] = _REFRESHJOBRETENTIONSETTINGSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshLogRetentionSettingsRequestProto'] = _REFRESHLOGRETENTIONSETTINGSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshLogRetentionSettingsResponseProto'] = _REFRESHLOGRETENTIONSETTINGSRESPONSEPROTO

class RefreshAdminAclsRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHADMINACLSREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshAdminAclsRequestProto)

class RefreshAdminAclsResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHADMINACLSRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshAdminAclsResponseProto)

class RefreshLoadedJobCacheRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHLOADEDJOBCACHEREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshLoadedJobCacheRequestProto)

class RefreshLoadedJobCacheResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHLOADEDJOBCACHERESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshLoadedJobCacheResponseProto)

class RefreshJobRetentionSettingsRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHJOBRETENTIONSETTINGSREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto)

class RefreshJobRetentionSettingsResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHJOBRETENTIONSETTINGSRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto)

class RefreshLogRetentionSettingsRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHLOGRETENTIONSETTINGSREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto)

class RefreshLogRetentionSettingsResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REFRESHLOGRETENTIONSETTINGSRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.mapreduce.RefreshLogRetentionSettingsResponseProto)


_HSADMINREFRESHPROTOCOLSERVICE = descriptor.ServiceDescriptor(
  name='HSAdminRefreshProtocolService',
  full_name='hadoop.mapreduce.HSAdminRefreshProtocolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=365,
  serialized_end=948,
  methods=[
  descriptor.MethodDescriptor(
    name='refreshAdminAcls',
    full_name='hadoop.mapreduce.HSAdminRefreshProtocolService.refreshAdminAcls',
    index=0,
    containing_service=None,
    input_type=_REFRESHADMINACLSREQUESTPROTO,
    output_type=_REFRESHADMINACLSRESPONSEPROTO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='refreshLoadedJobCache',
    full_name='hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLoadedJobCache',
    index=1,
    containing_service=None,
    input_type=_REFRESHLOADEDJOBCACHEREQUESTPROTO,
    output_type=_REFRESHLOADEDJOBCACHERESPONSEPROTO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='refreshJobRetentionSettings',
    full_name='hadoop.mapreduce.HSAdminRefreshProtocolService.refreshJobRetentionSettings',
    index=2,
    containing_service=None,
    input_type=_REFRESHJOBRETENTIONSETTINGSREQUESTPROTO,
    output_type=_REFRESHJOBRETENTIONSETTINGSRESPONSEPROTO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='refreshLogRetentionSettings',
    full_name='hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLogRetentionSettings',
    index=3,
    containing_service=None,
    input_type=_REFRESHLOGRETENTIONSETTINGSREQUESTPROTO,
    output_type=_REFRESHLOGRETENTIONSETTINGSRESPONSEPROTO,
    options=None,
  ),
])

class HSAdminRefreshProtocolService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _HSADMINREFRESHPROTOCOLSERVICE
class HSAdminRefreshProtocolService_Stub(HSAdminRefreshProtocolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _HSADMINREFRESHPROTOCOLSERVICE

# @@protoc_insertion_point(module_scope)
