language: python

python:
  - 2.7

cache:
  pip:
  apt:
  directories:
    - .tox

env:
 - TOX_ENV=py27-django18
 - TOX_ENV=py27-django19
 - TOX_ENV=py27-django110
 - TOX_ENV=py27-django111
 - TOX_ENV=py35-django18
 - TOX_ENV=py35-django19
 - TOX_ENV=py35-django110
 - TOX_ENV=py35-django111

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq $APT

after_failure:
 - cat /home/travis/.pip/pip.log

after_success:
 - coveralls

install:
 - pip install pip wheel
 - pip install -q coveralls flake8 tox

script:
 - env | sort
 - tox -e $TOX_ENV
 - flake8 --show-source --max-line-length=80 --exclude=.tox,docs,django_comments_xtd/tests,django_comments_xtd/__init__.py,django_comments_xtd/migrations django_comments_xtd/
