language: python
sudo: false
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3.5-5.8.0
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
  - COVERAGE_PROCESS_START=.coveragerc coverage run -m zope.testrunner --test-path=src -vv
after_success:
  - coverage combine
  - coveralls
notifications:
    email: false
cache: pip
