script:
language: python
python:
  - "2.7"
# Take out python3.x until python3 branch is merged
#  - "3.5"
# Travis uses Ubuntu 12.04 and 14.04. None of them have GSL2x in apt-get
# We have to install it from source (this will make the tests slower)
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install fftw3 fftw3-dev pkg-config
#  - sudo apt-get install latexmk
  - pip install numpy
  - ./install-gsl.sh 
#addons:
#    apt:
#        packages:
#            - texlive-latex-recommended
#            - texlive-latex-extra
#            - texlive-fonts-recommended
#            - texlive-fonts-extra
#            - dvipng
install: python setup.py install
script:
    - python tests/run_tests.py --debug --detailed-errors --verbose --process-restartworker 

# Check why the note creation process crashes
#    - make -C doc/0000-ccl_note
#after_success: 
#    if [[ -n "$GITHUB_API_KEY" ]; then
#        git checkout --orphan pdf
#        git rm -rf .
#        cp doc/0000-ccl_note/main.pdf 0000-ccl_note.pdf
#        git add -f 0000-ccl_note.pdf
#        git -c user.name='travis' -c user.email='travis' commit -m init
#        git push -q -f https://drphilmarshall:$GITHUB_API_KEY@github.com/DarkEnergyScienceCollaboration/CCL pdf
#    fi
