
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-08T14:39:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f911591299747b24b98f15f2943291974aa37b5c",
 "version": "0.1.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
