
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-06T05:32:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "82ef7663d99f09bf4bbb138243aea5e3d55e411e",
 "version": "v0.0.1-alpha.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
