
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-11T11:33:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "55c4f148d6f97615524b6d5ed007a42ba2a16fe1",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
