
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-18T13:13:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "10e1dc106f60f0acd06a9461abed57720b04f949",
 "version": "2017.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
