# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyBOT.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/pyBOT.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 47, 13))
        self.label.setObjectName("label")
        self.lblDebug = QtWidgets.QLabel(self.centralwidget)
        self.lblDebug.setGeometry(QtCore.QRect(60, 0, 47, 13))
        self.lblDebug.setText("")
        self.lblDebug.setObjectName("lblDebug")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setGeometry(QtCore.QRect(7, 16, 1071, 313))
        self.mainTab.setTabletTracking(False)
        self.mainTab.setStyleSheet("")
        self.mainTab.setTabPosition(QtWidgets.QTabWidget.West)
        self.mainTab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.mainTab.setObjectName("mainTab")
        self.tabBOT = QtWidgets.QWidget()
        self.tabBOT.setObjectName("tabBOT")
        self.groupBox = QtWidgets.QGroupBox(self.tabBOT)
        self.groupBox.setGeometry(QtCore.QRect(433, 0, 77, 64))
        self.groupBox.setObjectName("groupBox")
        self.rbtnFirefox = QtWidgets.QRadioButton(self.groupBox)
        self.rbtnFirefox.setGeometry(QtCore.QRect(10, 12, 66, 17))
        self.rbtnFirefox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbtnFirefox.setObjectName("rbtnFirefox")
        self.rbtnChrome = QtWidgets.QRadioButton(self.groupBox)
        self.rbtnChrome.setGeometry(QtCore.QRect(10, 27, 66, 17))
        self.rbtnChrome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbtnChrome.setObjectName("rbtnChrome")
        self.rbtnIE = QtWidgets.QRadioButton(self.groupBox)
        self.rbtnIE.setGeometry(QtCore.QRect(11, 42, 33, 17))
        self.rbtnIE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbtnIE.setObjectName("rbtnIE")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabBOT)
        self.groupBox_2.setGeometry(QtCore.QRect(432, 63, 104, 217))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 13, 91, 228))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnStart = QtWidgets.QPushButton(self.layoutWidget)
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 0, 0, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 1, 0, 1, 1)
        self.btnSwitch = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSwitch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSwitch.setObjectName("btnSwitch")
        self.gridLayout.addWidget(self.btnSwitch, 2, 0, 1, 1)
        self.btnOpenScript = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOpenScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpenScript.setObjectName("btnOpenScript")
        self.gridLayout.addWidget(self.btnOpenScript, 3, 0, 1, 1)
        self.btnSaveScript = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSaveScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSaveScript.setObjectName("btnSaveScript")
        self.gridLayout.addWidget(self.btnSaveScript, 4, 0, 1, 1)
        self.btnGetScript = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGetScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGetScript.setObjectName("btnGetScript")
        self.gridLayout.addWidget(self.btnGetScript, 5, 0, 1, 1)
        self.btnRunScript = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRunScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRunScript.setObjectName("btnRunScript")
        self.gridLayout.addWidget(self.btnRunScript, 6, 0, 1, 1)
        self.btnDebug = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDebug.setObjectName("btnDebug")
        self.gridLayout.addWidget(self.btnDebug, 7, 0, 1, 1)
        self.lsbxLog = QtWidgets.QListWidget(self.tabBOT)
        self.lsbxLog.setGeometry(QtCore.QRect(0, 0, 431, 281))
        self.lsbxLog.setObjectName("lsbxLog")
        self.txtCommand = QtWidgets.QLineEdit(self.tabBOT)
        self.txtCommand.setGeometry(QtCore.QRect(0, 283, 430, 20))
        self.txtCommand.setObjectName("txtCommand")
        self.btnSend = QtWidgets.QPushButton(self.tabBOT)
        self.btnSend.setGeometry(QtCore.QRect(433, 281, 100, 23))
        self.btnSend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSend.setObjectName("btnSend")
        self.txtScript = QtWidgets.QPlainTextEdit(self.tabBOT)
        self.txtScript.setGeometry(QtCore.QRect(0, 0, 431, 281))
        self.txtScript.setObjectName("txtScript")
        self.pnlScriptsData = QtWidgets.QFrame(self.tabBOT)
        self.pnlScriptsData.setGeometry(QtCore.QRect(0, 300, 571, 311))
        self.pnlScriptsData.setStyleSheet("background-color:#D7DEF7")
        self.pnlScriptsData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pnlScriptsData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlScriptsData.setObjectName("pnlScriptsData")
        self.label_2 = QtWidgets.QLabel(self.pnlScriptsData)
        self.label_2.setGeometry(QtCore.QRect(210, 0, 101, 16))
        self.label_2.setObjectName("label_2")
        self.tblScripts = QtWidgets.QTableView(self.pnlScriptsData)
        self.tblScripts.setGeometry(QtCore.QRect(8, 30, 551, 241))
        self.tblScripts.setObjectName("tblScripts")
        self.btnConfirmScriptSelection = QtWidgets.QPushButton(self.pnlScriptsData)
        self.btnConfirmScriptSelection.setGeometry(QtCore.QRect(396, 280, 75, 23))
        self.btnConfirmScriptSelection.setObjectName("btnConfirmScriptSelection")
        self.btnCancelScriptSelection = QtWidgets.QPushButton(self.pnlScriptsData)
        self.btnCancelScriptSelection.setGeometry(QtCore.QRect(480, 280, 75, 23))
        self.btnCancelScriptSelection.setObjectName("btnCancelScriptSelection")
        self.btnShowGrid = QtWidgets.QPushButton(self.tabBOT)
        self.btnShowGrid.setGeometry(QtCore.QRect(537, -1, 10, 310))
        self.btnShowGrid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShowGrid.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.btnShowGrid.setFlat(False)
        self.btnShowGrid.setObjectName("btnShowGrid")
        self.mainTab.addTab(self.tabBOT, icon, "")
        self.tabTASKS = QtWidgets.QWidget()
        self.tabTASKS.setObjectName("tabTASKS")
        self.mainTab.addTab(self.tabTASKS, "")
        self.chkTopMost = QtWidgets.QCheckBox(self.centralwidget)
        self.chkTopMost.setGeometry(QtCore.QRect(462, -1, 60, 17))
        self.chkTopMost.setObjectName("chkTopMost")
        self.lblTime = QtWidgets.QLabel(self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(40, 0, 71, 20))
        self.lblTime.setText("")
        self.lblTime.setObjectName("lblTime")
        self.lcdTime = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTime.setGeometry(QtCore.QRect(470, 330, 101, 31))
        self.lcdTime.setStyleSheet("color: rgb(0, 255, 0);")
        self.lcdTime.setDigitCount(8)
        self.lcdTime.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTime.setObjectName("lcdTime")
        self.pbCache = QtWidgets.QProgressBar(self.centralwidget)
        self.pbCache.setGeometry(QtCore.QRect(25, 330, 444, 31))
        self.pbCache.setProperty("value", 24)
        self.pbCache.setObjectName("pbCache")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.btnDebug.clicked.connect(MainWindow.alert)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyBOT - Automated Web Page\'s Navigator"))
        self.label.setText(_translate("MainWindow", "pyBOT"))
        self.groupBox.setTitle(_translate("MainWindow", "BROWSER\'s"))
        self.rbtnFirefox.setText(_translate("MainWindow", "&FIREFOX"))
        self.rbtnChrome.setText(_translate("MainWindow", "&CHROME"))
        self.rbtnIE.setText(_translate("MainWindow", "&IE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ACTION\'s"))
        self.btnStart.setText(_translate("MainWindow", "&START"))
        self.btnExit.setText(_translate("MainWindow", "E&XIT"))
        self.btnSwitch.setText(_translate("MainWindow", "SWITCH MODE"))
        self.btnOpenScript.setText(_translate("MainWindow", "OPEN FILE"))
        self.btnSaveScript.setText(_translate("MainWindow", "SAVE SCRIPT"))
        self.btnGetScript.setText(_translate("MainWindow", "GET SCRIPT"))
        self.btnRunScript.setText(_translate("MainWindow", "RUN SCRIPT"))
        self.btnDebug.setText(_translate("MainWindow", "DEBUG"))
        self.btnSend.setText(_translate("MainWindow", "S&END"))
        self.label_2.setText(_translate("MainWindow", "AVAILABLE SCRIPTS"))
        self.btnConfirmScriptSelection.setText(_translate("MainWindow", "CONFIRM"))
        self.btnCancelScriptSelection.setText(_translate("MainWindow", "CANCEL"))
        self.btnShowGrid.setText(_translate("MainWindow", ">"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tabBOT), _translate("MainWindow", "&BOT"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tabTASKS), _translate("MainWindow", "&TASK\'s"))
        self.chkTopMost.setText(_translate("MainWindow", "TopMost"))

import res_rc
