# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_sociodynamicreport_sociodynamicreportentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='remarks',
        ),
        migrations.AddField(
            model_name='mood',
            name='day_quality_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Day Quality Remarks'),
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Mood Remarks'),
        ),
        migrations.AddField(
            model_name='mood',
            name='productivity_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Productivity Remarks'),
        ),
        migrations.AddField(
            model_name='mood',
            name='stress_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Stress Remarks'),
        ),
    ]
