# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_daily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'Psychological', 'verbose_name_plural': 'Psychological'},
        ),
        migrations.AddField(
            model_name='mood',
            name='negatives',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Please name negative moments you have experienced today'),
        ),
        migrations.AddField(
            model_name='mood',
            name='positives',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Please name positive moments you have experienced today'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='day_quality',
            field=models.CharField(choices=[('very-good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('bad', 'Bad'), ('very-bad', 'Very Bad')], default=None, max_length=30, verbose_name='During the day I felt...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='day_quality_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Because...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('very-high', 'Very High'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('very-low', 'Very Low')], default=None, max_length=30, verbose_name='Right now I feel...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Because...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='productivity',
            field=models.CharField(choices=[('very-high', 'Very High'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('very-low', 'Very Low')], default=None, max_length=30, verbose_name='My Productivity was...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='productivity_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Because...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='stress',
            field=models.CharField(choices=[('very-high', 'Very High'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('very-low', 'Very Low')], default=None, max_length=30, verbose_name='Right now are you stressed...'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='stress_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Because...'),
        ),
    ]
