# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone.models.martian_standard_time


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20171008_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='addional_activities',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Additional Activities'),
        ),
        migrations.AddField(
            model_name='daily',
            name='scheduled_activities',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Scheduled Activities'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='remarks',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreport',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreport',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time'),
        ),
    ]
