# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20171009_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='addional_activities',
            new_name='unsheduled',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='scheduled_activities',
        ),
        migrations.AddField(
            model_name='daily',
            name='done',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Scheduled and Done Activities'),
        ),
        migrations.AddField(
            model_name='daily',
            name='unfinished',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Problems or Unfinished Activities'),
        ),
    ]
