# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20171009_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='done',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Scheduled and Done Activities'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='unfinished',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Problems or Unfinished Activities'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='unsheduled',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Activities'),
        ),
    ]
