# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import wheatgrass_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The article content.', max_length=500)),
                ('content', models.CharField(blank=True, help_text='The article content.', max_length=500000)),
                ('thumbnail', models.CharField(blank=True, help_text='The article thumbnail image.', max_length=500)),
                ('markdown', models.BooleanField(default=True, help_text='If True, Markdown formatting will be enabled.')),
                ('html', models.BooleanField(default=True, help_text='If True, HTML will be enabled.')),
                ('visible', models.BooleanField(default=False, help_text='If False, the article will not be publically visible.')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_file', models.FileField(upload_to=wheatgrass_blog.models.article_file_path)),
                ('article', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
