#- name: "Register resource count"
- name: "provision resource type : {{ res_def['res_type'] | default(res_def['type']) }}"
  include: "provision_{{ res_def['res_type'] | default(res_def['type']) }}.yml"
