# coding: utf-8

"""
    directus.io

    API for directus.io

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import directus_sdk
from directus_sdk.rest import ApiException
from directus_sdk.apis.settings_api import SettingsApi


class TestSettingsApi(unittest.TestCase):
    """ SettingsApi unit test stubs """

    def setUp(self):
        self.api = directus_sdk.apis.settings_api.SettingsApi()

    def tearDown(self):
        pass

    def test_get_settings(self):
        """
        Test case for get_settings

        Returns settings
        """
        pass

    def test_get_settings_for(self):
        """
        Test case for get_settings_for

        Returns settings for collection
        """
        pass

    def test_update_settings(self):
        """
        Test case for update_settings

        Update settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
