# coding: utf-8

"""
    directus.io

    API for directus.io

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import directus_sdk
from directus_sdk.rest import ApiException
from directus_sdk.apis.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """ FilesApi unit test stubs """

    def setUp(self):
        self.api = directus_sdk.apis.files_api.FilesApi()

    def tearDown(self):
        pass

    def test_create_file(self):
        """
        Test case for create_file

        Creates file
        """
        pass

    def test_get_file(self):
        """
        Test case for get_file

        Returns specific file by id
        """
        pass

    def test_get_files(self):
        """
        Test case for get_files

        Returns files
        """
        pass

    def test_update_file(self):
        """
        Test case for update_file

        Creates file
        """
        pass


if __name__ == '__main__':
    unittest.main()
