# coding: utf-8

"""
    directus.io

    API for directus.io

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import directus_sdk
from directus_sdk.rest import ApiException
from directus_sdk.models.get_settings_for import GetSettingsFor


class TestGetSettingsFor(unittest.TestCase):
    """ GetSettingsFor unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSettingsFor(self):
        """
        Test GetSettingsFor
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = directus_sdk.models.get_settings_for.GetSettingsFor()
        pass


if __name__ == '__main__':
    unittest.main()
