
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-12T10:15:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1272c9dc71333aa9c1e462032b8e93f8eaf61424",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
