language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
    - iverilog

install:
  - pip install pytest pytest-pythonpath pyverilog ipgen

script:
  - python -m pytest tests examples
