
'''
This file is automatically generated by setup.py, So don't edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.13.0.post2',
    'branch_nick': '(detached',
    'revision_id': 'bb5e7411c59c671ca45b51aab9c2df2c26af2860',
    'revno': 5425
}
