language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install tox
  - pip install tox-travis
  - pip install coveralls
  - pip install nose
script:
  - tox
deploy:
  provider: pypi
  user: choppsv1
  password:
    secure: VejRHCCsIK3ESiDVaSpQBh4oWb5ZycJ5dOBB0vZ3mPnNU06tojUi+J/IMTiIPLm1wPnJtH+qh8qvnxyEU8UsiS4KRR3skfZYLpoSCoja0RX/lkpoLYZ+AeWcCsJSvSHSzsd9UFPfrBRbo3kvog7+6uUWLCq6IViW5397Hdb9yIP1214KhxaSzf4e/5C5rMmsdYtIIuJRA4Z7U5Vb8JpBIQ2Eob7YoyD8FmOSW8e4ZMWTn3OJifd25C1k9AOR5LiCvyxAG/UYS3vHoPK3iZm5WFadubyFiK+4bwKGKPgwy+T6wZYdfqG4yLhULvDox5FYPI0XPByQiPHZukV7pSRZyMImcwIqptn5FykofYOeiIDeRxPyeCtrJisDB5eBqDnPQF4+NfeeCNB5brQK9lFYa9VT+FMvbRTmHcxA83/Xza/H/u6jZLp0Iz3SiwZxYl3Ibgw3yVecXpmTpRCTZySrA+xKBmZyiFy8mU904eMbqhIk+CrWvpTRI2dZ+xnf6+4Srp2507mgyULb6e98b5UW6/4XblqevcjR1fNiWGWPVrP/nRLmiyMxsNYBrA0YK+PLzyv0WtZSwrkS59K2H6clNvgGcUCKcIdEuMZ9gkVAPoSnaVCskXwFg/bmuaUHKWYKWgLtNk2MFWnKM8jPRRBEaNtdCflR3c2m+KPUCGa0MiE=
  on:
    tags: true
