
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-09T17:11:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "308e50d6c77dba1300da53901f44a650226f092f",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
