-
   name: Absorbance 200.00_nm
   unit: m-1
   description: absorbance at 200.00 nm wavelength

-
   name: Absorbance 202.50_nm
   unit: m-1
   description: absorbance at 202.50 nm wavelength

-
   name: rain intensity
   unit: mm/h
   description:

-
   name: wind speed
   unit: km/h
   description: wind speed in metric system
