
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-09T15:23:43+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8918d224e308b095db55877d6e8c65329b699bb0",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
