environment:
  matrix:
    - TOXENV: py26
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: flakes

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install --pre -U tox

build: false  # Not a C# project

test_script:
  - C:\Python36\scripts\tox
