
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6c8b997647b989cbbd6928b63ba6bbc9d7d2f2f9",
 "version": "1.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
