
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-29T10:30:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9868a35f4f9c8431a2806c5ba7a4c30b69b61599",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
