---

- include: apt.yml
  tags: [apt, server-hardening]

- include: sysctl.yml
  tags: [sysctl, server-hardening]

- include: users.yml
  tags: [users, server-hardening]

#- include_role:
#    name: dev-sec.ssh-hardening
#    tags: [ssh-hardening, server-hardening]

- include_role:
    name: ansible-fail2ban
    tags: [fail2ban, server-hardening]

- include_role:
    name: ansible-ufw
    tags: [ansible-ufw, server-hardening]

- include: hostname.yml
  tags: [hostname, server-hardening]