
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-07T08:52:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "01366049747030cd5cf157112f956580d4b16ac7",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
