
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-26T17:35:10-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cbf04e55f51bc5a224b6363f172d1e486e9e034",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
