language: python
sudo: false
python:
    - 2.7
install:
    - pip install -e .
    - pip install zope.testrunner coverage coveralls
script:
    - coverage run -m zope.testrunner --test-path=src --tests-pattern='^f?tests$' --ignore-new-thread=Dummy
after_success:
    - coveralls
notifications:
    email: false
