language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - SPHINX_VERSION=">=1.2, <1.3"
  - SPHINX_VERSION=">=1.3, <1.4"
  - SPHINX_VERSION=">=1.4, <1.5"
  - SPHINX_VERSION=">=1.5, <1.6"
  - SPHINX_VERSION=">=1.6, <1.7"

install:
 - pip install "sphinx $SPHINX_VERSION"
 - pip install -r requirements.txt

script:
 - python setup.py install
 - make test
