
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0c801380086226975b21aaaeb3d64474326fdbd5",
 "version": "0.1.post11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
