# coding: utf-8

"""
    Schul-Cloud Content API

    This is the specification for the content of Schul-Cloud. You can find more information in the [repository](https://github.com/schul-cloud/resources-api-v1). 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResourcePostData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, attributes=None, id=None):
        """
        ResourcePostData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'ResourceType',
            'attributes': 'Resource',
            'id': 'str'
        }

        self.attribute_map = {
            'type': 'type',
            'attributes': 'attributes',
            'id': 'id'
        }

        self._type = type
        self._attributes = attributes
        self._id = id

    @property
    def type(self):
        """
        Gets the type of this ResourcePostData.

        :return: The type of this ResourcePostData.
        :rtype: ResourceType
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ResourcePostData.

        :param type: The type of this ResourcePostData.
        :type: ResourceType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def attributes(self):
        """
        Gets the attributes of this ResourcePostData.

        :return: The attributes of this ResourcePostData.
        :rtype: Resource
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this ResourcePostData.

        :param attributes: The attributes of this ResourcePostData.
        :type: Resource
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")

        self._attributes = attributes

    @property
    def id(self):
        """
        Gets the id of this ResourcePostData.
        The id of the object which should be used instead of a generated id by the service. This includes everything you can put into the url path without the \"/\" and \"%HH\" hexadecimal encoded characters. The characters are specified in the url standard as \"segment\" https://www.w3.org/Addressing/URL/url-spec.txt page 14/15

        :return: The id of this ResourcePostData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ResourcePostData.
        The id of the object which should be used instead of a generated id by the service. This includes everything you can put into the url path without the \"/\" and \"%HH\" hexadecimal encoded characters. The characters are specified in the url standard as \"segment\" https://www.w3.org/Addressing/URL/url-spec.txt page 14/15

        :param id: The id of this ResourcePostData.
        :type: str
        """
        if id is not None and not re.search('([!*\"\'(),+a-zA-Z0-9$_@.&+\\-])+', id):
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/([!*\"'(),+a-zA-Z0-9$_@.&+\\-])+/`")

        self._id = id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResourcePostData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
