# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistedproduct',
            options={'ordering': ['-added'], 'verbose_name': 'Wish list product', 'verbose_name_plural': 'Wish list products'},
        ),
    ]
