# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('pcart_customers', '0009_auto_20170412_1252'),
        ('pcart_catalog', '0014_auto_20170411_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_visits', models.PositiveIntegerField(default=1, verbose_name='Number of visits')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pcart_customers.Customer', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pcart_catalog.Product', verbose_name='Product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='sites.Site', verbose_name='Site')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pcart_catalog.ProductVariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name_plural': 'Product pages visits',
                'verbose_name': 'Product page visit',
                'ordering': ['-changed'],
            },
        ),
    ]
