# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenario_exporter_s3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetinfo',
            old_name='name',
            new_name='data_set_name',
        ),
        migrations.RenameField(
            model_name='datasetinfo',
            old_name='table',
            new_name='table_name',
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='database_name',
            field=models.TextField(default=None, help_text='The name of the database with the model tables'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='manager',
            field=models.TextField(default=None, help_text='The name of the model manager to use'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='model_name',
            field=models.TextField(default=None, help_text='The name of the model class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='model_pk',
            field=models.TextField(default=None, help_text='The PK of the model instance'),
            preserve_default=False,
        ),
    ]
