# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenario_exporter_s3', '0002_auto_20170922_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetinfo',
            old_name='database_name',
            new_name='db_name',
        ),
        migrations.RemoveField(
            model_name='datasetinfo',
            name='data_set_name',
        ),
        migrations.RemoveField(
            model_name='datasetinfo',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='datasetinfo',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='datasetinfo',
            name='model_pk',
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='date_field',
            field=models.TextField(default=None, help_text='Name of date field to filter by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetinfo',
            name='point_field',
            field=models.TextField(default=None, help_text='Name of point field to filter by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetinfo',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, help_text='The bounding box to limit exported rows', srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetinfo',
            name='timerange',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None, help_text='The time range to limit exported rows'),
            preserve_default=False,
        ),
    ]
