# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plenario_exporter_s3', '0003_auto_20170922_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='The job identifier', primary_key=True, serialize=False),
        ),
    ]
