# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plenario_exporter_s3', '0004_auto_20170922_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetinfo',
            old_name='db_name',
            new_name='meta_model_app_label',
        ),
        migrations.RenameField(
            model_name='datasetinfo',
            old_name='table_name',
            new_name='meta_model_class_name',
        ),
    ]
