# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenario_exporter_s3', '0005_auto_20170922_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetinfo',
            name='meta_model_pk',
            field=models.TextField(default=None, help_text='The primary key of the meta model instance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetinfo',
            name='meta_model_app_label',
            field=models.TextField(help_text='The app label of the meta model'),
        ),
        migrations.AlterField(
            model_name='datasetinfo',
            name='meta_model_class_name',
            field=models.TextField(help_text='The class name of the meta model'),
        ),
    ]
