
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-22T14:23:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "196d399a71d1f051227cae2a58e69fb4d99c6bd6",
 "version": "1.5.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
