# -*- coding: utf-8 -*-

#    _                                 _
#   /_\    __ _   ___   _ __  __ _    (_)  ___
#  //_\\  / _` | / _ \ | '__|/ _` |   | | / _ \
# /  _  \| (_| || (_) || |  | (_| | _ | || (_) |
# \_/ \_/ \__, | \___/ |_|   \__,_|(_)|_| \___/
#        |___/


SUCCESS = 0
LOGOUT_E_OTHER = 100
LOGOUT_E_USER = 101
LOGOUT_E_NET = 102
LOGOUT_E_KICKED = 103
LOGOUT_E_PACKET = 104
LOGOUT_E_TOKENEXPIRED = 105
LOGOUT_E_OLDVERSION = 106
LOGOUT_E_TOKENWRONG = 107
LOGOUT_E_ALREADY_LOGOUT = 108
LOGIN_E_OTHER = 200
LOGIN_E_NET = 201
LOGIN_E_FAILED = 202
LOGIN_E_CANCEL = 203
LOGIN_E_TOKENEXPIRED = 204
LOGIN_E_OLDVERSION = 205
LOGIN_E_TOKENWRONG = 206
LOGIN_E_TOKEN_KICKED = 207
LOGIN_E_ALREADY_LOGIN = 208
JOINCHANNEL_E_OTHER = 300
SENDMESSAGE_E_OTHER = 400
SENDMESSAGE_E_TIMEOUT = 401
QUERYUSERNUM_E_OTHER = 500
QUERYUSERNUM_E_TIMEOUT = 501
QUERYUSERNUM_E_BYUSER = 502
LEAVECHANNEL_E_OTHER = 600
LEAVECHANNEL_E_KICKED = 601
LEAVECHANNEL_E_BYUSER = 602
LEAVECHANNEL_E_LOGOUT = 603
LEAVECHANNEL_E_DISCONN = 604
INVITE_E_OTHER = 700
INVITE_E_REINVITE = 701
INVITE_E_NET = 702
INVITE_E_PEEROFFLINE = 703
INVITE_E_TIMEOUT = 704
INVITE_E_CANTRECV = 705
GENERAL_E = 1000
GENERAL_E_FAILED = 1001
GENERAL_E_UNKNOWN = 1002
GENERAL_E_NOT_LOGIN = 1003
GENERAL_E_WRONG_PARAM = 1004
