
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1448768d81867f0320637c3a0b4b4460a483e076",
 "version": "0.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
