---
- name: "Provision dummy resources by looping on count"
  dummy:
    state: present
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    count: "{{ res_def['count'] | default(1) }}"
  register: outputitem
  when: res_def['type']=="dummy_node"

- name: "set tmp var"
  set_fact:
    tmp: ["{{ outputitem }}"]

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_dummy: "{{ topology_outputs_dummy + tmp }}"

