# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gblprocess',
            old_name='job_id',
            new_name='request_id',
        ),
    ]
