# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 07:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170713_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSourceData',
            fields=[
                ('id', models.AutoField(help_text=b'Sequence Number', primary_key=True, serialize=False)),
                ('investor_id', models.CharField(help_text=b'Investor ID', max_length=40)),
                ('loan_id', models.CharField(help_text=b'Loan ID', max_length=40)),
                ('cutoff_date', models.DateField(blank=True, help_text=b'Cutoff Date', null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'master_source_data',
            },
        ),
    ]
