# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_mastersourcedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqheader',
            name='end_date',
            field=models.DateField(blank=True, help_text=b'Start Date', null=True),
        ),
        migrations.AlterField(
            model_name='reqheader',
            name='schedule_next',
            field=models.CharField(blank=True, choices=[(b'Initiated', b'Current Request is Initiated'), (b'Completed', b'Prior Request has Completed'), (b'Null', b'Null')], default=b'Initiated', help_text=b'Schedule Next Request When', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reqheader',
            name='start_date',
            field=models.DateField(blank=True, help_text=b'Start Date', null=True),
        ),
    ]
