
spectrogram:
   fft:
      window: 256
      overlap: 192
      window-function: hamming
      # boxcar triang blackman hamming hann bartlett flattop parzen bohman
      # blackmanharris nuttall barthann
   calculations:
      high-pass: 1250
      low-pass: 10000
      threshold: 14
      log10-freq: false
   colors:
      invert: false
      border: paleblue
      line: deepskyblue
      eraser: yellow
      cursor: red
   scale-ratio: 8

main-window:
   maximized: false
   menu: *main-menu
   toolbars:
      - name: modes
        items: [ quit, bar, mode_normal, mode_cursor, mode_eraser, undo ]
        position: top
        visible: true
        style: *TextBesideIcon
      - name: songs
        items: [ prev_song, next_song, add_songs ]
        position: top
        visible: true
        style: *TextBesideIcon
      - name: zoom
        items: [ fit ]
        position: top
        visible: true
        style: *TextBesideIcon
   statusbar:
      visible: true

data-files:
   log-file:
   header-format: "Song\tFrequency Excursion\tNotes\n"
   data-format: "{name}\t{fex:.3f}\t{notes}\n"

