
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-05T06:31:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fe3888468f6a8b3d78b049bf5962a90b62bcdc5",
 "version": "0.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
