# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBannerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pcart_plugins_bigbannerpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title_1', models.CharField(blank=True, default='', max_length=255, verbose_name='Title 1')),
                ('title_2', models.CharField(blank=True, default='', max_length=255, verbose_name='Title 2')),
                ('descrition', models.TextField(blank=True, default='', verbose_name='Description')),
                ('template_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Template name')),
                ('extra_css_classes', models.CharField(blank=True, default='', max_length=255, verbose_name='Extra CSS classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
