# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('pcart_plugins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigbannerpluginmodel',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bigbannerpluginmodel',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_banners', to='filer.Image', verbose_name='Image'),
        ),
    ]
