# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:26
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_plugins', '0002_auto_20171002_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbannerpluginmodel',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
