# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_plugins', '0003_auto_20171002_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigbannerpluginmodel',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
        migrations.AddField(
            model_name='bigbannerpluginmodel',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
    ]
