# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapproval', '0002_auto_20171001_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='owned_pages',
        ),
    ]
