
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-30T22:04:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3689dd3f82620eb34f5b8fe3b5ea0b2abcfb360a",
 "version": "2.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
