# coding: utf-8
# Generated by setup.py for PyCBC on 2017-09-10 15:34:56 +0000.

version = '1.8.1'
date = '2017-09-10 14:10:05 +0000'
release = True
last_release = '1.8.1'

git_hash = 'bc03655f8a0522f0fc2781801aaeccae93c00ed2'
git_branch = 'None'
git_tag = 'v1.8.1'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2017-09-10 15:34:56 +0000'
git_verbose_msg = """Branch: None
Tag: v1.8.1
Id: bc03655f8a0522f0fc2781801aaeccae93c00ed2
Builder: Travis CI User <travis@example.org>
Build date: 2017-09-10 15:34:56 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
