sudo: required

services:
  - docker

python:
  - '2.7'

env:
  matrix:
  - TOX_ENV=flake8

install:
  - pip install .
  - pip install tox

script:
  - tox -e $TOX_ENV
  - pip list --format=columns | grep pyvcloud
  - python -c 'import pkg_resources; print(pkg_resources.require("pyvcloud")[0].version)'
  - vca --version
  - vcd version
