
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a3cf19e2f1d8a3706f22915c54a115ad03950736",
 "version": "0.post.dev610"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
