# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '1.0.0.dev3'
VERSION = '1.0.0.dev3'
FULL_VERSION = '1.0.0.dev3'
GIT_REVISION = '6e191240ad07e41938a516e7f2f39a7495961fc0'
GIT_VERSION = '1.0.0.dev3+6e19124'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
