
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-14T14:46:50+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d1b9df81e6789ed1d754f66f72aed0c4b60a2c4",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
