# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 16:47
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django_sharding_library.fields
import django_sharding_library.id_generation_strategies


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgressharduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='postgressharduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='postgrescustomautoidmodel',
            name='id',
            field=django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='tests.PostgresCustomIDModelBackupField', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='tests.PostgresCustomIDModelBackupField')),
        ),
        migrations.AlterField(
            model_name='postgrescustomidmodel',
            name='id',
            field=django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='tests.PostgresCustomIDModelBackupField', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='tests.PostgresCustomIDModelBackupField')),
        ),
        migrations.AlterField(
            model_name='postgressharduser',
            name='shard',
            field=models.CharField(blank=True, choices=[('app_shard_001', 'app_shard_001'), ('app_shard_002', 'app_shard_002'), ('app_shard_003', 'app_shard_003'), ('app_shard_004', 'app_shard_004')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='postgressharduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='shardedbyforiegnkeymodel',
            name='shard',
            field=django_sharding_library.fields.ShardForeignKeyStorageField(on_delete=django.db.models.deletion.CASCADE, shard_group='default', to='tests.ShardStorageTable'),
        ),
        migrations.AlterField(
            model_name='shardstoragetable',
            name='shard',
            field=models.CharField(choices=[('app_shard_001', 'app_shard_001'), ('app_shard_002', 'app_shard_002'), ('app_shard_003', 'app_shard_003'), ('app_shard_004', 'app_shard_004')], max_length=120),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='tests.ShardedTestModelIDs', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='tests.ShardedTestModelIDs')),
        ),
        migrations.AlterField(
            model_name='unshardedtestmodel',
            name='id',
            field=django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='tests.ShardedTestModelIDs', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='tests.ShardedTestModelIDs')),
        ),
        migrations.AlterField(
            model_name='user',
            name='shard',
            field=models.CharField(blank=True, choices=[('app_shard_001', 'app_shard_001'), ('app_shard_002', 'app_shard_002'), ('app_shard_003', 'app_shard_003'), ('app_shard_004', 'app_shard_004')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
