
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-30T16:47:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a10b8a5d9933e9cb064b0c62f73187a1ec2a0748",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
