# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppResourcePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.TextField()),
                ('can_list', models.BooleanField(default=True)),
                ('can_retrieve', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_destroy', models.BooleanField(default=False)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_permission', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'db_table': 'sunrise_contrib_oauth_app_resource_permission',
            },
        ),
        migrations.CreateModel(
            name='RequestHandshake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('from_origin', models.CharField(max_length=100)),
                ('access_key', models.CharField(max_length=100, null=True)),
                ('secret_key', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('REF_CODE', models.CharField(max_length=30, null=True)),
                ('counterparty', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'request_hand_shake',
            },
        ),
    ]
