
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-01T06:26:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "33dacf615ec006b07dfab77035fe5d5d4bb061ea",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
