
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "18f2634cd098efa027572de4de76af148b578219",
 "version": "0.1.post14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
