
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-12T14:52:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a42196d571fa4ab68f9a8a5f986a1db7c532fd6",
 "version": "0.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
