# coding: utf-8

"""
    Schul-Cloud Content API

    This is the specification for the content of Schul-Cloud. You can find more information in the [repository](https://github.com/schul-cloud/resources-api-v1). 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Jsonapi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, version=None, meta=None):
        """
        Jsonapi - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'version': 'str',
            'meta': 'JsonapiMeta'
        }

        self.attribute_map = {
            'version': 'version',
            'meta': 'meta'
        }

        self._version = version
        self._meta = meta

    @property
    def version(self):
        """
        Gets the version of this Jsonapi.
        The version of the jsonapi which is supported http://jsonapi.org/format/#document-jsonapi-object

        :return: The version of this Jsonapi.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this Jsonapi.
        The version of the jsonapi which is supported http://jsonapi.org/format/#document-jsonapi-object

        :param version: The version of this Jsonapi.
        :type: str
        """
        allowed_values = ["1.0"]
        if version not in allowed_values:
            raise ValueError(
                "Invalid value for `version` ({0}), must be one of {1}"
                .format(version, allowed_values)
            )

        self._version = version

    @property
    def meta(self):
        """
        Gets the meta of this Jsonapi.

        :return: The meta of this Jsonapi.
        :rtype: JsonapiMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """
        Sets the meta of this Jsonapi.

        :param meta: The meta of this Jsonapi.
        :type: JsonapiMeta
        """

        self._meta = meta

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Jsonapi):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
