
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-03T02:03:42+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac77d25b7cfde2f470e0bcafc6193a6c44bb51a1",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
