
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7d1e8b1181b6dd8c1df1c68ee5b13ff224cdc7cc",
 "version": "1.1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
