language: python

# for container-y goodness:
sudo: false

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
- "pip install --upgrade pip setuptools"
- "pip install -Ue .[test]"

script: coverage run -m pytest

after_success:
  - coveralls


jobs:
  include:

    - stage: coverage
      python: 3.6
      after_success: skip

      install: "pip install -U coveralls-check"
      script: "coveralls-check $TRAVIS_COMMIT"

    - stage: release
      if: tag IS present
      python: 3.6
      script: skip
      # work around https://github.com/travis-ci/travis-ci/issues/8337:
      after_success: true

      install:
      - "pip install --upgrade pip setuptools"
      - "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: f28D/cZT27Ejv++FA8Er1GIwD9KG6t82J/AHUlzGvbjQpP9js6TIgZ51nxhf/lhJrACNONOrd3XhjMc1QRgkCKOLHjSHpozO0qPa2lZ3+4c+BP5lZTXmI3uS8YBaidOpWFZjkxf38zK59yab7ntkl02UNibo5RWzoaYJIPcjizA=
        on:
          tags: true
          repo: Simplistix/mush
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
