
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-09T12:59:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1c1cf6bb7ed239b49084eddd134e41b67d2b9d9",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
