channels:
  - conda-forge
name: py35
dependencies:
- openssl
- pip
- python=3.5.3
- readline
- setuptools
- sqlite
- wheel
- zlib
- pip:
  - Sphinx
  - graphviz
  - git+https://github.com/wheerd/sphinx-autodoc-typehints.git@napoleon-master#egg=sphinx-autodoc-napoleon-typehints
  - hopcroftkarp
  - multiset>=2.0,<3.0
  - setuptools_scm
