# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name_row', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('total_max_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
