class Prijmeni:
    """ Třída zapouzdřující chování obyčejného příjmení.. """
    def __init__(self, nazev, nazev2):
        self.nazev = nazev
        self.nazev2 = nazev2


prijmenis = []

def Init():
    prijmenis.append(Prijmeni("Novák", "Nováková")) 
    prijmenis.append(Prijmeni("Koudelka", "Koudelková")) 
    prijmenis.append(Prijmeni("Procházka", "Procházková")) 
    prijmenis.append(Prijmeni('Adamčík', 'Adamčíková'))
    prijmenis.append(Prijmeni('Adámek', 'Adámková'))
    prijmenis.append(Prijmeni('Adrián', 'Adriánová'))
    prijmenis.append(Prijmeni('Aizner', 'Aiznerová'))
    prijmenis.append(Prijmeni('Antalík', 'Antalíková'))
    prijmenis.append(Prijmeni('Antl', 'Antlová'))
    prijmenis.append(Prijmeni('Antončík', 'Antončíková'))
    prijmenis.append(Prijmeni('Antošík', 'Antošíková'))
    prijmenis.append(Prijmeni('Apolenář', 'Apolenářová'))
    prijmenis.append(Prijmeni('Astaloš', 'Astalošová'))
    prijmenis.append(Prijmeni('Ašenbryl', 'Ašenbrylová'))
    prijmenis.append(Prijmeni('Augustýn', 'Augustýnková'))
    prijmenis.append(Prijmeni('Bednář', 'Bednářová'))
    prijmenis.append(Prijmeni('Bubák', 'Bubáková'))
    prijmenis.append(Prijmeni('Babčák', 'Babčáková'))
    prijmenis.append(Prijmeni('Babin', 'Babincová'))
    prijmenis.append(Prijmeni('Bábor', 'Báborová'))
    prijmenis.append(Prijmeni('Babuka', 'Babuková'))
    prijmenis.append(Prijmeni('Badura', 'Badurová'))
    prijmenis.append(Prijmeni('Bachel', 'Bachelová'))
    prijmenis.append(Prijmeni('Bachman', 'Bachmannová'))
    prijmenis.append(Prijmeni('Bednařík', 'Bednaříková'))
    prijmenis.append(Prijmeni('Balada', 'Baladová'))
    prijmenis.append(Prijmeni('Balarin', 'Balarinová'))
    prijmenis.append(Prijmeni('Balatka', 'Balatková'))
    prijmenis.append(Prijmeni('Balcar', 'Balcarová'))
    prijmenis.append(Prijmeni('Balcarek', 'Balcarková'))
    prijmenis.append(Prijmeni('Bleša', 'Blešová'))
    prijmenis.append(Prijmeni('Baltair', 'Baltairová'))
    prijmenis.append(Prijmeni('Balvín', 'Balvínová'))
    prijmenis.append(Prijmeni('Caban', 'Cabanová'))
    prijmenis.append(Prijmeni('Cabuk', 'Cabuková'))
    prijmenis.append(Prijmeni('Cahlík', 'Cahlíková'))
    prijmenis.append(Prijmeni('Cakl', 'Caklová'))
    prijmenis.append(Prijmeni('Calta', 'Caltová'))
    prijmenis.append(Prijmeni('Cápík', 'Cápíková'))
    prijmenis.append(Prijmeni('Cardal', 'Cardalová'))
    prijmenis.append(Prijmeni('Cejhon', 'Cejhonová'))
    prijmenis.append(Prijmeni('Cekl', 'Ceklová'))
    prijmenis.append(Prijmeni('Celerin', 'Celerinová'))
    prijmenis.append(Prijmeni('Černý', 'Černá'))
    prijmenis.append(Prijmeni('Cibulka', 'Cibulková'))
    prijmenis.append(Prijmeni('Cidlík', 'Cidlíková'))
    prijmenis.append(Prijmeni('Císař', 'Císařová'))
    prijmenis.append(Prijmeni('Cigler', 'Ciglerová'))
    prijmenis.append(Prijmeni('Cichra', 'Cichrová'))
    prijmenis.append(Prijmeni('Cikl', 'Ciková'))
    prijmenis.append(Prijmeni('Ciprys', 'Ciprysová'))
    prijmenis.append(Prijmeni('Čagánek', 'Čagánková'))
    prijmenis.append(Prijmeni('Čapek', 'Čapková'))
    prijmenis.append(Prijmeni('Čapla', 'Čaplová'))
    prijmenis.append(Prijmeni('Černý', 'Černocká'))
    prijmenis.append(Prijmeni('Částka', 'Částková'))
    prijmenis.append(Prijmeni('Čavajda', 'Čavajdová'))
    prijmenis.append(Prijmeni('Čechal', 'Čechalová'))
    prijmenis.append(Prijmeni('Čepelík', 'Čepelíková'))
    prijmenis.append(Prijmeni('Červenka', 'Červenková'))
    prijmenis.append(Prijmeni('Černošek', 'Černošková'))
    prijmenis.append(Prijmeni('Červík', 'Červíková'))
    prijmenis.append(Prijmeni('Česák', 'Česáková'))
    prijmenis.append(Prijmeni('Češek', 'Češková'))
    prijmenis.append(Prijmeni('Češka', 'Češková'))
    prijmenis.append(Prijmeni('Čičela', 'Čičelová'))
    prijmenis.append(Prijmeni('Čokina', 'Čokinová'))
    prijmenis.append(Prijmeni('Čtvrtníček', 'Čtvrtníčková'))
    prijmenis.append(Prijmeni('Čubák', 'Čubáková'))
    prijmenis.append(Prijmeni('Čunek', 'Čunková'))
    prijmenis.append(Prijmeni('Cuřín', 'Cuřínová'))
    prijmenis.append(Prijmeni('Dratva', 'Dratvová'))
    prijmenis.append(Prijmeni('Dajka', 'Dajkvá'))
    prijmenis.append(Prijmeni('Dalibor', 'Daliborová'))
    prijmenis.append(Prijmeni('Damaška', 'Damašková'))
    prijmenis.append(Prijmeni('Dančák', 'Dančáková'))
    prijmenis.append(Prijmeni('Dandel', 'Dandelová'))
    prijmenis.append(Prijmeni('Danihel', 'Danihelková'))
    prijmenis.append(Prijmeni('Danko', 'Danková'))
    prijmenis.append(Prijmeni('Daráš', 'Darášová'))
    prijmenis.append(Prijmeni('Drábek', 'Drábková'))
    prijmenis.append(Prijmeni('Darebník', 'Derebníková'))
    prijmenis.append(Prijmeni('Darebníček', 'Darebníčková'))
    prijmenis.append(Prijmeni('Drtikol', 'Drtikolová'))
    prijmenis.append(Prijmeni('Drásal', 'Drásalová'))
    prijmenis.append(Prijmeni('David', 'Davidová'))
    prijmenis.append(Prijmeni('Dědek', 'Dětková'))
    prijmenis.append(Prijmeni('Dedek', 'Dedková'))
    prijmenis.append(Prijmeni('Didov', 'Didová'))
    prijmenis.append(Prijmeni('Dikoras', 'Dikorasová'))
    prijmenis.append(Prijmeni('Ditrich', 'Ditrichová'))
    prijmenis.append(Prijmeni('Djakov', 'Djakovová'))
    prijmenis.append(Prijmeni('Dlouhý', 'Dlouhá'))
    prijmenis.append(Prijmeni('Dobenčák', 'Dobenčáková'))
    prijmenis.append(Prijmeni('Dobrovský', 'Dobrovská'))
    prijmenis.append(Prijmeni('Dobřický', 'Dobřická'))
    prijmenis.append(Prijmeni('Dočekal', 'Dočekalová'))
    prijmenis.append(Prijmeni('Dohnalík', 'Dohnalíková'))
    prijmenis.append(Prijmeni('Donutil', 'Donutilová'))
    prijmenis.append(Prijmeni('Dokoupil', 'Dokoupilová'))
    prijmenis.append(Prijmeni('Domanín', 'Domanínová'))
    prijmenis.append(Prijmeni('Donáth', 'Donáthová'))

def PrintAll():
    for prijmeni in prijmenis:
        print(prijmeni.nazev)
