dist: trusty
sudo: false

language: python

matrix:
  include:
    - python: '2.7'
    - python: 'pypy'
      env: PYENV_VERSION=pypy2.7-portable-5.8.0 PYENV_VERSION_STRING='PyPy 5.8.0'
    - python: '3.3'
    - python: '3.4'
    - python: '3.5'
    - python: '3.6'
    - python: 'pypy3'
      env: PYENV_VERSION=pypy3.5-portable-5.8.0 PYENV_VERSION_STRING='PyPy 5.8.0'

before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install -e .

script: py.test --flake8 --cov

after_success:
  coveralls

cache:
  - pip
  - directories:
    - "${PYENV_CACHE_PATH:-$HOME/.pyenv_cache}"
