# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='figure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figure',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalnote',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
    ]
