# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone.models.martian_standard_time


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20171008_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
    ]
