# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20171008_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Personal Diary'},
        ),
    ]
