
strictness: high

max-line-length: 120

member-warnings: true

doc-warnings: false

test-warnings: true

pylint:
  options:
    init-import: true
    dummy-variables-rgx: _$|dummy|___
    max-parents: 20

  disable:
    # optparse
    - deprecated-module

    - bare-except
    - broad-except
    - invalid-name
    - multiple-statements
    - no-self-use
    - protected-access
    - too-many-arguments
    - too-many-branches
    - too-many-instance-attributes
    - too-many-lines
    - too-many-locals
    - too-many-return-statements
    - too-many-statements
    - unused-argument
    - trailing-newlines

    # tofix: style
    - consider-using-ternary
    - no-else-return
    - len-as-condition
    - arguments-differ

pyflakes:
  disable:
    - F401
    - F403

mccabe:
  run: false

