#config_version=4
mode:
  start_events: start_mode2
  stop_events: stop_mode2
  priority: 200
  start_priority: 1
  game_mode: False

slide_player:
  show_slide_mode2:
    slide_mode2:
      action: play
  show_slide_mode2_frame:
    slide_mode2_frame:
      action: play
  remove_slide_mode2_frame:
    slide_mode2_frame:
      action: remove

slides:
  slide_mode2:
  - type: text
    text: Slide Mode2
  slide_mode2_frame:
  - type: slide_frame
    name: frame_mode2
    width: 800
    height: 600