- name: "DEBUG:: provisioning resource group {{ res_grp }}"
  debug:
    msg: "The current Resource Group obj is {{ res_grp }} "

- name: "Unset the authvar from previous run"
  set_fact:
    auth_var: ""

- name: "Set cred profile"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] | default('default') }}"

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ res_grp['credentials']['filename']  }}"
    cred_type: "aws"
    cred_path: "{{ creds_path | default(default_credentials_path) }}"
    driver: "file"
  register: auth_var
  ignore_errors: true

- name: "Set auth_var "
  set_fact:
    auth_var: "{{ auth_var['output'][cred_profile] | default('') }}"
  ignore_errors: true

- name: "provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name']}}"]
  loop_control:
    loop_var: res_item
