branches:
  only:
    - master
    - dev
sudo: false
language: python
python:
  - "2.7"
install: 
  - pip install pip --upgrade
  - pip install .
  - pip install .[server]
script:
  - python runtests.py all
  - python runtests.py complete
