"""
Djanggo Asservio Core settings.
"""
from django.conf import settings

DICTIONARIES_CODE_MAX_LENGTH = \
    getattr(settings, 'CORE_DICTIONARIES_CODE_MAX_LENGTH', 20)

DICTIONARIES_NAME_MAX_LENGTH = \
    getattr(settings, 'CORE_DICTIONARIES_NAME_MAX_LENGTH', 50)

DICTIONARIES_DESCRIPTION_MAX_LENGTH = \
    getattr(settings, 'CORE_DICTIONARIES_DESCRIPTION_MAX_LENGTH', 1000)

DICTIONARIES_NAME_UNIQUENESS = \
    getattr(settings, 'CORE_DICTIONARIES_NAME_UNIQUENESS', False)

DICTIONARIES_TIME_AUDIT_ENABLED = \
    getattr(settings, 'CORE_DICTIONARIES_TIME_AUDIT_ENABLED', False)

GENERAL_MODELS_TIME_AUDIT_ENABLED = \
    getattr(settings, 'CORE_GENERAL_MODELS_TIME_AUDIT_ENABLED', False)
