extensions = ["sphinx.ext.autodoc"]
templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"
project = "pyderasn"
copyright = "2017, Sergey Matveev"
author = "Sergey Matveev"
version = "1.0"
release = "1.0"
language = None
exclude_patterns = ["_build"]
pygments_style = "sphinx"
todo_include_todos = False
html_theme = "classic"
html_static_path = ["_static"]
html_sidebars = {}
