language: python
python:
  - '2.7'
addons:
  apt:
    packages:
      - pandoc
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: rjosephwright
    password:
      secure: Z0xUBYpuA/4XiGtc58REda08eUFn76OKeeK+kA+Jbp5uCIHj6nuCvxBMcFxifvB0qC/Jr1ebfemV2XlurjLCDcgrqwtQ8CLKPdocF9xyKUIobrKllkEO+a+rPzYrCsRhvk1aZHHdHOTfbbZdfBK8uSujhZnyMkR2lWJdWp7MabcFpZ9CCrshKmOSKDpy0l2Ghh+/rhKL4+xyOp0ybD/hp9IfjkreUhZcKmJoeZMGycvJRhxizu+Ky2nIJEQMmK/5eRMUmnlpEoIAtTDO7+w5Ot2eshZK7lp4mHO43YDRHUCRa/5xYkGrMHb2DkF1yl+k8YOxhjoHRO28UDQV42f8KHH0HMdaIJrj92jbBvvOlxF7MK/y3M0EtHWj5XKhirTaVa8EtI+3zE0bIPGkwBx9t78K+jJ4/vZ5UsxUGQRLJ7el8MIJG1Eyu7x+x78iCO5Ux4wVGH+ORF/p0Zxp4e2/HMBtOI66DA2VePhItkmPOd1QQ1qKYVSlVaSgetuDzb8flUclg60ZoX6iP9zVBYeR0oY0cDSqfQ1nUKVh2ASimMlUiZSou1JCvr8VM08JiIGWdTGvzL6QxFKZLZ/sIcjDT5YIHOB4I1h75NoMZlQNXdoAUCFSvYGlx+whogpLM2d0nlAZfKAGtOZafE0sbaNDfR7jPXdmq+Oxz3W/sYEMt2E=
    on:
      tags: true
    distributions: sdist bdist_wheel
    repo: cloudboss/bossimage
