
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-01T22:58:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee0c5846f97ca0855f6fe084ae8525a2e6d9661e",
 "version": "1.0.b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
