
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-26T20:32:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad16c3d18b4f1fbcced8335cbd0ff141fb6c42d4",
 "version": "0.23.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
